# Generated by Django 3.2.14 on 2022-07-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgapp', '0004_auto_20220719_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default=1, help_text='В формате НЕХ', max_length=7, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
